export const FoodDetails = [{
    "id":1,
    "title": "Biryani",
    "type": "MainC",
    "description": "Biryani isn’t technically a curry but is a curried, aromatic dish of basmati rice, spices, meat, herbs and either curd or yoghurt",
    "filename": "0.jpg",
    "height": 600,
    "width": 400,
    "price": 5.44,
    "rating": 4.5,
    "quantity": 0,
    "img":"https://images.food52.com/7f0yncraWeYUJG_lLbH2ie1xd6g=/2016x1344/d815e816-4664-472e-990b-d880be41499f--chicken-biryani-recipe.jpg"
    
  }, {
    "id":2,
    "title": "CHICKEN 65",
    "type": "fruit",
    "description": "Essentially, it consists of deep-fried chicken pieces that are then coated in a super spicy sauce. The curry itself can vary depending on where it’s being made but usually the sauce needs to contain Kashmiri red chillies for that certain kick",
    "filename": "1.jpg",
    "height": 450,
    "width": 299,
    "price": 4.49,
    "rating": 4,
    "quantity": 0,
    "img":"https://recipesofhome.com/wp-content/uploads/2020/08/chicken-65-recipe.jpg"
  }, {
    "id":3,
    "title": "Asparagus",
    "type": "vegetable",
    "description": "Asparagus with ham on the wooden table",
    "filename": "2.jpg",
    "height": 450,
    "width": 299,
    "price": 18.95,
    "rating": 3,
    "quantity": 0,
    "img":"https://www.eatme.eu/media/ydhoq1jg/eat-me-groene-asperges-200-gram.jpg?anchor=center&mode=crop&width=1200&height=630&rnd=132629798811500000"
  }, {
    "id":4,
    "title": "Green smoothie",
    "type": "dairy",
    "description": "Glass of green smoothie with quail egg's yolk, served with cocktail tube, green apple and baby spinach leaves over tin surface.",
    "filename": "3.jpg",
    "height": 600,
    "width": 399,
    "price": 17.68,
    "rating": 4,
    "quantity": 0,
    "img":"https://www.cookingclassy.com/wp-content/uploads/2019/07/green-smoothie-10.jpg"
  }, {
    "id":5,
    "title": "Raw legums",
    "type": "vegetable",
    "description": "Raw legums on the wooden table",
    "filename": "4.jpg",
    "height": 450,
    "width": 299,
    "price": 17.11,
    "rating": 2,
    "quantity": 0,
    "img":"https://imagesvc.meredithcorp.io/v3/jumpstartpure/image/?url=https%3A%2F%2Fcf-images.us-east-1.prod.boltdns.net%2Fv1%2Fstatic%2F1033249144001%2F7c8b611c-a1c1-4b12-abfd-57602436878e%2Fa9bba3c3-287b-4e3d-81e1-d1719c62502b%2F1280x720%2Fmatch%2Fimage.jpg&w=640&h=360&q=90&c=cc"
  }, {
    "id":6,
    "title": "Baking cake",
    "type": "dairy",
    "description": "Baking cake in rural kitchen - dough  recipe ingredients (eggs, flour, sugar) on vintage wooden table from above.",
    "filename": "5.jpg",
    "height": 450,
    "width": 675,
    "price": 11.14,
    "rating": 4,
    "quantity": 0,
  }, {
    "id":7,
    "title": "Pesto with basil",
    "type": "vegetable",
    "description": "Italian traditional pesto with basil, chesse and oil",
    "filename": "6.jpg",
    "height": 450,
    "width": 299,
    "price": 18.19,
    "rating": 2,
    "quantity": 0,
  }, {
    "id":8,
    "title": "Hazelnut in black ceramic bowl",
    "type": "vegetable",
    "description": "Hazelnut in black ceramic bowl on old wooden background. forest wealth. rustic style. selective focus",
    "filename": "7.jpg",
    "height": 450,
    "width": 301,
    "price": 27.35,
    "rating": 0,
    "quantity": 0,
  }, {
    "id":9,
    "title": "Fresh stawberry",
    "type": "fruit",
    "description": "Sweet fresh stawberry on the wooden table",
    "filename": "8.jpg",
    "height": 600,
    "width": 399,
    "price": 28.59,
    "rating": 4,
    "quantity": 0,
  }, {
    "id":10,
    "title": "Lemon and salt",
    "type": "fruit",
    "description": "Rosemary, lemon and salt on the table",
    "filename": "9.jpg",
    "height": 450,
    "width": 299,
    "price": 15.79,
    "rating": 5,
    "quantity": 0,
  }]